main: com.Sagacious_.KitpvpStats.Core
name: PVPStats
version: 1.8
author: Sagacious_
softdepend: [PlaceholderAPI, MVdWPlaceholderAPI, Vault]
commands: 
  stats:
   aliases: [statistics]
  leaderboardrefresh:
   usage: /<command>
  moveleaderboard:
   aliases: [movelb] 
  adminreset:
   aliases: [ar]
  statsreset:
   aliases: [sr]  