leaderboard-format: '&6%number%. &e%name% &8| &r%integer%'
leaderboard-update-time: 120

leaderboard-kills-enabled: false
leaderboard-kills-header: '&7Top 10 kills'
leaderboard-kills-location: 'world, 0.0, 5.0, 0.0'

leaderboard-deaths-enabled: false
leaderboard-deaths-header: '&7Top 10 Deaths'
leaderboard-deaths-location: 'world, 0.0, 5.0, 0.0'

leaderboard-killstreak-enabled: false
leaderboard-killstreak-header: '&7Top 10 Killstreaks'
leaderboard-killstreak-location: 'world, 0.0, 5.0, 0.0'

stats-command: 
  - '&8-=-=-[ &aMy Statistics &8]-=-=-'
  - '&7'
  - '&aKills &8> &r%kills%'
  - '&aDeaths &8> &r%deaths%'
  - '&aKillstreak &8> &r%killstreak%'
  - '&aTop Killstreak &8> &r%top_killstreak%'
  - '&aLevel &8> &r%level%'
  
  
  
level-kills-interval: 25

#Each string represents a higher level
levels:
  - '&6Rookie' #Lvl 1.
  - '&aKiller' #Lvl 2.
  - '&cMurderer' #Lvl 3.

#Requires Vault  
use-format: false
format: "&7[%level%&7] %prefix%&7%player%&8: &7%suffix%%message%"


#Anti stats booster, set 0 to disable
antistats-max-kills: 15
antistats-max-kills-time: 300
antistats-timeout: 600
antistats-message: '&cYou have killed a single player too many times, you will not increase your statistics for &410 minutes'
